export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_LISTONE_REQUEST = 'PRODUCT_LISTONE_REQUEST';
export const PRODUCT_LISTONE_SUCCESS = 'PRODUCT_LISTONE_SUCCESS';
export const PRODUCT_LISTONE_FAIL = 'PRODUCT_LISTONE_FAIL';

export const CREATE_COMMENT_PRODUCT_REQUEST = 'CREATE_COMMENT_PRODUCT_REQUEST';
export const CREATE_COMMENT_PRODUCT_SUCCESS = 'CREATE_COMMENT_PRODUCT_SUCCESS';
export const CREATE_COMMENT_PRODUCT_FAIL = 'CREATE_COMMENT_PRODUCT_FAIL';

export const DELETE_COMMENT_PRODUCT_REQUEST = 'DELETE_COMMENT_PRODUCT_REQUEST';
export const DELETE_COMMENT_PRODUCT_SUCCESS = 'DELETE_COMMENT_PRODUCT_SUCCESS';
export const DELETE_COMMENT_PRODUCT_FAIL = 'DELETE_COMMENT_PRODUCT_FAIL';