export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_LISTONE_REQUEST = 'PRODUCT_LISTONE_REQUEST';
export const PRODUCT_LISTONE_SUCCESS = 'PRODUCT_LISTONE_SUCCESS';
export const PRODUCT_LISTONE_FAIL = 'PRODUCT_LISTONE_FAIL';